[package]
name = "install-nothing"
version = "0.1.0"
edition = "2021"
authors = ["NoName"]
description = "A nostalgic infinite installer simulator"

[dependencies]
crossterm = "0.27"
rand = "0.8"
colored = "2.1"
